apiVersion: v1
kind: ConfigMap
metadata:
  name: paypulse-postgres-config
  namespace: paypulse
  labels:
    app: paypulse-postgres
data:
  POSTGRES_USER: "paypulse"
  POSTGRES_DB: "paypulse"
  # Postgres uses this directory for its data files
  PGDATA: "/var/lib/postgresql/data/pgdata"
