apiVersion: v1
kind: Service
metadata:
  name: paypulse-frontend
  namespace: paypulse
  labels:
    app: paypulse-frontend
spec:
  type: ClusterIP
  selector:
    app: paypulse-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
